" Date: 2017-04-01
" Author: Michael Crilly

" Vundle related
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'vim-airline/vim-airline'
Plugin 'https://github.com/kien/ctrlp.vim'
Plugin 'rust-lang/rust.vim'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()
filetype plugin indent on

" Custom stuff by me
let mapleader = ","

" From here we're working from:
" https://gist.github.com/simonista/8703722
set nocompatible
filetype off
syntax on
filetype plugin indent on
set modelines=0
set number
set ruler
set visualbell
set encoding=utf-8
set wrap
set textwidth=79
set tabstop=2
set shiftwidth=2
set expandtab
set listchars=tab:▸\ ,eol:¬
set t_Co=256
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
" wget https://raw.github.com/altercation/vim-colors-solarized/master/colors/solarized.vim
colorscheme solarized


" From here we're working from:
" http://joshldavis.com/2014/04/05/vim-tab-madness-buffers-vs-tabs/
" tab controls
nmap <leader>tn :enew<CR>
nmap <leader>l :BuffergatorOpen<cr>
nmap <leader>k :bnext<CR>
nmap <leader>j :bprevious<CR>
nmap <leader>tc :bp <BAR> bd#<CR>

let g:buffergator_viewport_split_policy = 'N'
let g:buffergator_suppress_keymaps = 1
nmap <leader>jj :BuffergatorMruCyclePrev<cr>
nmap <leader>kk :BuffergatorMruCycleNext<cr>
nmap <leader>bl :BuffergatorOpen<cr>

" CntrlP bundle related config
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
\}
let g:ctrlp_working_path_mode = 'r'

nmap <leader>p :CtrlP<CR>

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'

" From here we're working from my twisted mind:
" window controls
nmap <leader>ws :split<CR>
nmap <leader>wc :q<CR>
set laststatus=2
set backspace=2

" From: https://superuser.com/questions/163589/switch-buffers-in-vim-without-saving-to-a-currently-modified-file
set hidden
