" Date: 2017-04-01
" Author: Michael Crilly

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'fatih/vim-go', { 'tag': '*' }
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdcommenter'
call plug#end()

" Custom stuff by me
let mapleader = ","

" From here we're working from:
" https://gist.github.com/simonista/8703722
set nocompatible
filetype off
syntax on
filetype plugin indent on
set modelines=0
set number relativenumber
set ruler
set visualbell
set encoding=utf-8
set wrap
set textwidth=79
set tabstop=4
set shiftwidth=4
set noexpandtab
set listchars=tab:▸\ ,eol:¬
set t_Co=256
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
" wget https://raw.github.com/altercation/vim-colors-solarized/master/colors/solarized.vim
colorscheme solarized

" From here we're working from:
" http://joshldavis.com/2014/04/05/vim-tab-madness-buffers-vs-tabs/
" tab controls
nmap <leader>tn :enew<CR>
nmap <leader>tc :bp <BAR> bd#<CR>
nmap <leader>tr :bprev<CR>
nmap <leader>ty :bnext<CR>

nmap <leader>p :Files<CR>
nmap <leader>P :GFile<CR>

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'

" From here we're working from my twisted mind:
" window controls
nmap <leader>whs :split<CR>
nmap <leader>wvs :vsplit<CR>
nmap <leader>wc :q<CR>
nmap <leader>wq <C-W><C-J>
nmap <leader>we <C-W><C-K>
set laststatus=2
set backspace=2

" vim-go commands
nmap <leader>gr :GoRun<CR>
nmap <leader>gb :GoBuild<CR>
nmap <leader>gi :GoInstall<CR>
nmap <leader>gt :GoTest<CR>
nmap <leader>gl :GoLint<CR>
nmap <leader>gf :GoFmt<CR>

let g:go_fmt_command = "goimports"

" From: https://github.com/python-mode/python-mode/issues/56
set completeopt=longest,menuone

" From: https://superuser.com/questions/163589/switch-buffers-in-vim-without-saving-to-a-currently-modified-file
set hidden
